import { Drop } from './types'

export const ramadanReset: Drop = {
  slug: 'ramadan-reset',
  title: 'Ramadan Reset',
  subtitle: 'Curated for your most intentional month yet.',
  category: 'spiritual',
  coverImage: '/images/drops/ramadan-reset.jpg',
  publishedAt: '2024-02-15',
  featured: true,
  intro: `Every Ramadan I try to enter differently — more prepared, more present. This year I put together the things that have actually helped me slow down, reset, and make space for what matters. These are not just products. They are invitations.`,
  sections: [
    {
      title: 'For Your Space',
      description: 'Create an environment that invites stillness.',
      brands: [
        {
          id: 'space-1',
          name: 'Salam Candles',
          description: 'Hand-poured soy candles with oud and amber notes that transform any room into a sanctuary.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Shop Now',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'space-2',
          name: 'Noor Home',
          description: 'Minimalist prayer rugs designed for the modern Muslim home.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Explore',
          ctaHref: '#',
          featured: false,
        },
        {
          id: 'space-3',
          name: 'Barakah Decor',
          description: 'Islamic calligraphy prints that bring intention to your walls.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'View Collection',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
    {
      title: 'For Your Routine',
      description: 'Small anchors that help you stay grounded through the month.',
      brands: [
        {
          id: 'routine-1',
          name: 'Dhikr Journal',
          description: 'A guided journal for daily reflection, gratitude, and spiritual tracking.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Get Yours',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'routine-2',
          name: 'Quran App Pro',
          description: 'Ad-free Quran reading with personalized Ramadan reading plans.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Download',
          ctaHref: '#',
          featured: false,
        },
        {
          id: 'routine-3',
          name: 'Tasbih Co',
          description: 'Handcrafted prayer beads made from ethically sourced materials.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Shop',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
    {
      title: 'For Your Heart',
      description: 'Nourishment beyond the physical fast.',
      brands: [
        {
          id: 'heart-1',
          name: 'Seekers Guidance',
          description: 'On-demand Islamic courses to deepen your understanding this Ramadan.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Start Learning',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'heart-2',
          name: 'Productive Muslim',
          description: 'Resources for balancing productivity with spiritual presence.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Explore',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
  ],
  reflection: {
    insight: 'Ramadan is not a month of deprivation. It is a month of redirection — a chance to taste what it feels like when dunya loosens its grip.',
    question: 'What is one thing you want to release this Ramadan — and one thing you want to build in its place?',
    reference: 'Inspired by the concept of tawbah — returning.',
  },
  ctaText: 'Join The Circle for exclusive Ramadan content',
  ctaHref: '/circle',
}
