import { Drop } from './types'

export const selfCareRoutine: Drop = {
  slug: 'self-care-routine',
  title: 'The Self-Care Routine',
  subtitle: 'Because taking care of yourself is an act of worship.',
  category: 'lifestyle',
  coverImage: '/images/drops/self-care.jpg',
  publishedAt: '2024-02-01',
  featured: false,
  intro: `Nobody told me that self-care and spirituality could live in the same breath. For a long time I separated them — the deen stuff over here, the personal stuff over there. This drop is for the version of us that does not split anymore.`,
  sections: [
    {
      title: 'Morning Anchors',
      description: 'Start before the world asks anything of you.',
      brands: [
        {
          id: 'morning-1',
          name: 'Fajr Alarm',
          description: 'A gentle alarm app designed around prayer times — not productivity culture.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Download',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'morning-2',
          name: 'Sunrise Dates',
          description: 'Premium Medjool dates for your morning energy — sunnah approved.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Order',
          ctaHref: '#',
          featured: false,
        },
        {
          id: 'morning-3',
          name: 'Nur Matcha',
          description: 'Organic matcha from a Muslim-owned brand for a calm, focused start.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Shop',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
    {
      title: 'Body Care',
      description: 'Clean, intentional, halal-friendly options.',
      brands: [
        {
          id: 'body-1',
          name: 'Amara Skincare',
          description: 'Halal-certified skincare that actually works — no compromises.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Explore',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'body-2',
          name: 'Oud Essentials',
          description: 'Alcohol-free perfume oils that last from Fajr to Isha.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Shop Scents',
          ctaHref: '#',
          featured: false,
        },
        {
          id: 'body-3',
          name: 'Safa Beauty',
          description: 'Wudu-friendly nail polish and halal makeup essentials.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'View Collection',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
    {
      title: 'Wind Down',
      description: 'End the day like it mattered.',
      brands: [
        {
          id: 'wind-1',
          name: 'Quran Night Light',
          description: 'A soft-glow lamp with rotating ayah displays for peaceful nights.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Get Yours',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'wind-2',
          name: 'Sabr Sleep',
          description: 'Weighted blankets and sleep accessories designed for rest — not hustle.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Shop Rest',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
  ],
  reflection: {
    insight: 'Your body has a right over you. This is not a lifestyle trend — it is a prophetic teaching. Rest, nourishment, and care are not luxuries. They are obligations to yourself.',
    question: 'What does your body need from you right now that you keep postponing?',
    reference: "Inspired by the hadith: 'Your body has a right over you.'",
  },
  ctaText: 'Join The Circle — more for the whole you',
  ctaHref: '/circle',
}
