import { Drop } from './types'

export const texasHalalGuide: Drop = {
  slug: 'texas-halal-guide',
  title: 'Texas Halal Guide',
  subtitle: "The Muslim woman's guide to eating well in DFW.",
  category: 'food',
  coverImage: '/images/drops/texas-halal.jpg',
  publishedAt: '2024-03-01',
  featured: true,
  intro: `Texas surprised me. The halal food scene here is unlike anything I expected — layered, diverse, and deeply community-driven. These are the spots I actually go to, the ones I send friends to, and the ones that feel like home.`,
  sections: [
    {
      title: 'Best Bites in DFW',
      description: 'From weeknight dinners to special occasions.',
      brands: [
        {
          id: 'food-1',
          name: 'Zatar Lebanese',
          description: 'Authentic Lebanese cuisine with generous portions and even more generous hospitality.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'View Menu',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'food-2',
          name: 'Halal Guys DFW',
          description: 'The legendary NYC street food, now with Texas-sized servings.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Order Now',
          ctaHref: '#',
          featured: false,
        },
        {
          id: 'food-3',
          name: 'Istanbul Grill',
          description: 'Turkish flavors that transport you — without leaving Irving.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Explore',
          ctaHref: '#',
          featured: false,
        },
        {
          id: 'food-4',
          name: 'Afrah Mediterranean',
          description: 'Family-style Mediterranean perfect for gatherings and celebrations.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Reserve',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
    {
      title: 'Hidden Gems',
      description: 'The spots the algorithm has not found yet.',
      brands: [
        {
          id: 'gem-1',
          name: "Mama's Kitchen",
          description: 'Hole-in-the-wall Pakistani spot with the best biryani in North Texas.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Find It',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'gem-2',
          name: 'Saffron House',
          description: 'Indian-Pakistani fusion in a strip mall — trust me on this one.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Discover',
          ctaHref: '#',
          featured: false,
        },
        {
          id: 'gem-3',
          name: 'Noor Bakery',
          description: 'Fresh-baked naan, baklava, and pastries that sell out by noon.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Visit',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
    {
      title: 'Muslim-Owned to Support',
      description: 'Beyond the meal — businesses worth backing.',
      brands: [
        {
          id: 'support-1',
          name: 'Crescent Catering',
          description: 'Full-service halal catering for weddings, events, and corporate functions.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Get Quote',
          ctaHref: '#',
          featured: true,
        },
        {
          id: 'support-2',
          name: 'Baraka Grocery',
          description: 'Your one-stop shop for halal meats and Middle Eastern ingredients.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Shop',
          ctaHref: '#',
          featured: false,
        },
        {
          id: 'support-3',
          name: 'Tayyib Farms',
          description: 'Local, ethical, halal meat delivered to your door.',
          image: '/images/drops/placeholder.jpg',
          ctaLabel: 'Subscribe',
          ctaHref: '#',
          featured: false,
        },
      ],
    },
  ],
  reflection: {
    insight: 'There is something sacred about sharing a meal in a space where you do not have to ask if it is halal. That ease is a form of belonging.',
    question: 'Where in Texas have you felt most at home — and what made it feel that way?',
  },
  ctaText: 'Feature your business in Muslim Texas',
  ctaHref: '/muslim-texas',
}
